-- Generated by d-migrate 0.9.5
-- Source: neutral schema v1.0.0 "m-trace"
-- Target: sqlite

CREATE TABLE "projects" (
    "project_id" TEXT NOT NULL,
    PRIMARY KEY ("project_id")
);

CREATE TABLE "playback_events" (
    "ingest_sequence" INTEGER PRIMARY KEY AUTOINCREMENT,
    "project_id" TEXT NOT NULL,
    "session_id" TEXT NOT NULL,
    "event_name" TEXT NOT NULL,
    "client_timestamp" TEXT NOT NULL,
    "server_received_at" TEXT NOT NULL,
    "sequence_number" INTEGER,
    "sdk_name" TEXT NOT NULL,
    "sdk_version" TEXT NOT NULL,
    "schema_version" TEXT NOT NULL,
    "meta" TEXT,
    "delivery_status" TEXT NOT NULL DEFAULT 'accepted',
    "trace_id" TEXT,
    "span_id" TEXT,
    "correlation_id" TEXT,
    CONSTRAINT "chk_playback_events_delivery_status" CHECK (delivery_status IN ('accepted', 'duplicate_suspected', 'replayed'))
);

CREATE TABLE "stream_sessions" (
    "session_id" TEXT NOT NULL,
    "project_id" TEXT NOT NULL REFERENCES "projects"("project_id") ON DELETE RESTRICT,
    "state" TEXT NOT NULL DEFAULT 'active',
    "started_at" TEXT NOT NULL,
    "last_seen_at" TEXT NOT NULL,
    "ended_at" TEXT,
    "event_count" INTEGER NOT NULL DEFAULT 0,
    "correlation_id" TEXT,
    CONSTRAINT "chk_stream_sessions_state" CHECK (state IN ('active', 'stalled', 'ended')),
    PRIMARY KEY ("session_id")
);

CREATE INDEX "idx_playback_events_session_canonical" ON "playback_events" ("project_id", "session_id", "server_received_at", "sequence_number", "ingest_sequence");

CREATE INDEX "idx_playback_events_dedup" ON "playback_events" ("project_id", "session_id", "sequence_number");

CREATE INDEX "idx_stream_sessions_project_started" ON "stream_sessions" ("project_id", "started_at", "session_id");

CREATE INDEX "idx_stream_sessions_state" ON "stream_sessions" ("state");
