-- V7: Sample-Rate-Persistenz auf Session-Ebene für plan-0.12.6
-- Tranche 4 (RAK-85 / R-10). Hand-gepflegt analog V2..V6;
-- d-migrate `schema-generate` berührt ausschließlich V1__m_trace.sql.
--
-- Zweck:
--   `0.4.0` bis `0.12.5` markierten Sampled-Sessions (`sampleRate <
--   1`) nur über die Operator-Konfiguration des Player-SDK — der
--   Server konnte nicht zwischen „voll-gesampelt" und „teilweise
--   gesampelt" unterscheiden, was Lücken-Erkennung im Read-Pfad
--   unmöglich machte (R-10 im Risk-Backlog).
--
--   `0.12.6` zieht die Markierung auf Session-Ebene nach: das SDK
--   schickt ab dieser Version `meta.session_sample_rate` als Pflicht-
--   Feld für jede Session mit `sampleRate < 1`. Der Server
--   normalisiert den Float auf Integer-ppm (parts per million) und
--   persistiert den **erstmaligen** Wert pro Session immutable. Spätere
--   Events mit abweichendem Wert lösen Drift-Counter aus, überschreiben
--   den Wert aber nicht (`UPDATE … WHERE sample_rate_ppm = 1000000`-
--   Pattern für Single-Set).
--
-- Spaltenform:
--   - INTEGER NOT NULL DEFAULT 1000000 — `1_000_000` = `SAMPLE_RATE_FULL`
--     (voll gesampelt, kein Sub-1-Wert eingegangen). Bereich
--     `[1, 1_000_000]`.
--   - Integer statt REAL: Vergleiche (`= 1000000` für Immutability,
--     `< 1000000` für Sampled-Detection) bleiben deterministisch ohne
--     Float-Drift. Float-Wire-Konvertierung lebt im Adapter
--     (`round(x * 1_000_000)`).
--   - DEFAULT 1_000_000: Sessions vor V7 werden konservativ als
--     voll-gesampelt gelesen (false-positive „kein Sampling" ist
--     akzeptabel; false-negative „doch Sampling" wäre irreführend).
--
-- Rollback:
--   `ALTER TABLE stream_sessions DROP COLUMN sample_rate_ppm;` —
--   verfügbar ab SQLite 3.35 (2021-03), die `modernc.org/sqlite`-
--   Version ist deutlich jünger. Index-Pflege nicht nötig — die
--   Spalte ist nicht indiziert (Read-Pfade scannen die Session-Zeile
--   ohnehin pro Detail-Request, kein Multi-Session-Filter über
--   sample_rate_ppm geplant).

ALTER TABLE "stream_sessions"
    ADD COLUMN "sample_rate_ppm" INTEGER NOT NULL DEFAULT 1000000;
