-- Generated by d-migrate 0.9.12
-- Source: neutral schema v1.0.0 "m-trace"
-- Target: postgresql

CREATE TABLE "auth_issuance_counters" (
    "bucket_key" TEXT,
    "capacity" INTEGER NOT NULL,
    "refill_per_second" DOUBLE PRECISION NOT NULL,
    "tokens" DOUBLE PRECISION NOT NULL,
    "last_at" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    PRIMARY KEY ("bucket_key")
);

CREATE TABLE "ingest_endpoints" (
    "endpoint_id" TEXT,
    "protocol" TEXT NOT NULL,
    "listen_host" TEXT NOT NULL,
    "listen_port" INTEGER NOT NULL,
    "path_template" TEXT NOT NULL,
    "lab_stack" TEXT NOT NULL,
    "public_url_hint" TEXT NOT NULL,
    CONSTRAINT "chk_ingest_endpoints_protocol" CHECK (protocol IN ('srt', 'rtmp')),
    PRIMARY KEY ("endpoint_id")
);

CREATE TABLE "media_server_targets" (
    "target_id" TEXT,
    "kind" TEXT NOT NULL,
    "config_path" TEXT NOT NULL,
    "hls_url_template" TEXT NOT NULL,
    "control_api_url" TEXT NOT NULL DEFAULT '',
    CONSTRAINT "chk_media_server_targets_kind" CHECK (kind IN ('mediamtx', 'srs')),
    PRIMARY KEY ("target_id")
);

CREATE TABLE "playback_events" (
    "ingest_sequence" BIGSERIAL,
    "project_id" TEXT NOT NULL,
    "session_id" TEXT NOT NULL,
    "event_name" TEXT NOT NULL,
    "client_timestamp" TEXT NOT NULL,
    "server_received_at" TEXT NOT NULL,
    "sequence_number" INTEGER,
    "sdk_name" TEXT NOT NULL,
    "sdk_version" TEXT NOT NULL,
    "schema_version" TEXT NOT NULL,
    "meta" TEXT,
    "delivery_status" TEXT NOT NULL DEFAULT 'accepted',
    "trace_id" TEXT,
    "span_id" TEXT,
    "correlation_id" TEXT,
    "time_skew_warning" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "chk_playback_events_delivery_status" CHECK (delivery_status IN ('accepted', 'duplicate_suspected', 'replayed')),
    PRIMARY KEY ("ingest_sequence")
);

CREATE TABLE "projects" (
    "project_id" TEXT,
    PRIMARY KEY ("project_id")
);

CREATE TABLE "ingest_streams" (
    "stream_id" TEXT,
    "project_id" TEXT,
    "display_name" TEXT NOT NULL,
    "protocol" TEXT NOT NULL,
    "endpoint_id" TEXT NOT NULL,
    "target_id" TEXT NOT NULL,
    "routing_rule_id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ready',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "fk_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") ON DELETE RESTRICT,
    CONSTRAINT "chk_ingest_streams_protocol" CHECK (protocol IN ('srt', 'rtmp')),
    CONSTRAINT "chk_ingest_streams_status" CHECK (status IN ('ready', 'live', 'ended', 'disabled')),
    PRIMARY KEY ("project_id", "stream_id")
);

CREATE TABLE "project_token_generations" (
    "token_id" TEXT,
    "project_id" TEXT NOT NULL,
    "key_hash" TEXT NOT NULL UNIQUE,
    "fingerprint" TEXT NOT NULL,
    "not_before" TEXT NOT NULL,
    "grace_until" TEXT,
    "expires_at" TEXT,
    "revoked_at" TEXT,
    "created_at" TEXT NOT NULL,
    "rotated_from" TEXT,
    CONSTRAINT "fk_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") ON DELETE CASCADE,
    PRIMARY KEY ("token_id")
);

CREATE TABLE "srt_health_samples" (
    "id" BIGSERIAL,
    "project_id" TEXT NOT NULL,
    "stream_id" TEXT NOT NULL,
    "connection_id" TEXT NOT NULL,
    "source_observed_at" TEXT,
    "source_sequence" TEXT,
    "collected_at" TEXT NOT NULL,
    "ingested_at" TEXT NOT NULL,
    "rtt_ms" DOUBLE PRECISION NOT NULL,
    "packet_loss_total" INTEGER NOT NULL,
    "packet_loss_rate" DOUBLE PRECISION,
    "retransmissions_total" INTEGER NOT NULL,
    "available_bandwidth_bps" INTEGER NOT NULL,
    "throughput_bps" INTEGER,
    "required_bandwidth_bps" INTEGER,
    "sample_window_ms" INTEGER,
    "source_status" TEXT NOT NULL,
    "source_error_code" TEXT NOT NULL,
    "connection_state" TEXT NOT NULL,
    "health_state" TEXT NOT NULL,
    CONSTRAINT "fk_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") ON DELETE RESTRICT,
    CONSTRAINT "chk_srt_health_samples_source_status" CHECK (source_status IN ('ok', 'unavailable', 'partial', 'stale', 'no_active_connection')),
    CONSTRAINT "chk_srt_health_samples_source_error_code" CHECK (source_error_code IN ('none', 'source_unavailable', 'no_active_connection', 'partial_sample', 'stale_sample', 'parse_error')),
    CONSTRAINT "chk_srt_health_samples_connection_state" CHECK (connection_state IN ('connected', 'no_active_connection', 'unknown')),
    CONSTRAINT "chk_srt_health_samples_health_state" CHECK (health_state IN ('healthy', 'degraded', 'critical', 'unknown')),
    PRIMARY KEY ("id")
);

CREATE TABLE "stream_sessions" (
    "session_id" TEXT,
    "project_id" TEXT,
    "state" TEXT NOT NULL DEFAULT 'active',
    "started_at" TEXT NOT NULL,
    "last_seen_at" TEXT NOT NULL,
    "ended_at" TEXT,
    "event_count" INTEGER NOT NULL DEFAULT 0,
    "correlation_id" TEXT,
    "end_source" TEXT,
    "sample_rate_ppm" INTEGER NOT NULL DEFAULT 1000000,
    CONSTRAINT "fk_0" FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") ON DELETE RESTRICT,
    CONSTRAINT "chk_stream_sessions_state" CHECK (state IN ('active', 'stalled', 'ended')),
    CONSTRAINT "chk_stream_sessions_end_source" CHECK (end_source IS NULL OR end_source IN ('client', 'sweeper')),
    PRIMARY KEY ("project_id", "session_id")
);

CREATE TABLE "ingest_routing_rules" (
    "rule_id" TEXT,
    "project_id" TEXT NOT NULL,
    "stream_id" TEXT NOT NULL,
    "target_id" TEXT NOT NULL,
    "mode" TEXT NOT NULL DEFAULT 'single',
    "enabled" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "fk_0" FOREIGN KEY ("project_id", "stream_id") REFERENCES "ingest_streams" ("project_id", "stream_id") ON DELETE CASCADE,
    CONSTRAINT "fk_1" FOREIGN KEY ("target_id") REFERENCES "media_server_targets" ("target_id") ON DELETE RESTRICT,
    CONSTRAINT "chk_ingest_routing_rules_mode" CHECK (mode IN ('single')),
    CONSTRAINT "chk_ingest_routing_rules_enabled" CHECK (enabled IN (0, 1)),
    PRIMARY KEY ("rule_id")
);

CREATE TABLE "stream_keys" (
    "key_id" TEXT,
    "project_id" TEXT NOT NULL,
    "stream_id" TEXT NOT NULL,
    "key_hash" TEXT NOT NULL,
    "fingerprint" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "deactivated_at" TEXT,
    CONSTRAINT "fk_0" FOREIGN KEY ("project_id", "stream_id") REFERENCES "ingest_streams" ("project_id", "stream_id") ON DELETE CASCADE,
    PRIMARY KEY ("key_id")
);

CREATE TABLE "stream_lifecycle_events" (
    "event_id" TEXT,
    "project_id" TEXT NOT NULL,
    "stream_id" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "occurred_at" TEXT NOT NULL,
    "received_at" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "key_fingerprint" TEXT NOT NULL DEFAULT '',
    "connection_id" TEXT NOT NULL DEFAULT '',
    "reason" TEXT NOT NULL DEFAULT '',
    CONSTRAINT "fk_0" FOREIGN KEY ("project_id", "stream_id") REFERENCES "ingest_streams" ("project_id", "stream_id") ON DELETE CASCADE,
    CONSTRAINT "chk_stream_lifecycle_events_kind" CHECK (kind IN ('stream_started', 'stream_ended')),
    CONSTRAINT "chk_stream_lifecycle_events_source" CHECK (source IN ('local-smoke', 'mediamtx-hook')),
    PRIMARY KEY ("event_id")
);

CREATE TABLE "stream_session_boundaries" (
    "project_id" TEXT,
    "session_id" TEXT,
    "kind" TEXT,
    "network_kind" TEXT,
    "adapter" TEXT,
    "reason" TEXT,
    "client_timestamp" TEXT NOT NULL,
    "server_received_at" TEXT NOT NULL,
    CONSTRAINT "fk_0" FOREIGN KEY ("project_id", "session_id") REFERENCES "stream_sessions" ("project_id", "session_id") ON DELETE CASCADE,
    CONSTRAINT "chk_stream_session_boundaries_kind" CHECK (kind IN ('network_signal_absent')),
    CONSTRAINT "chk_stream_session_boundaries_network_kind" CHECK (network_kind IN ('manifest', 'segment')),
    CONSTRAINT "chk_stream_session_boundaries_adapter" CHECK (adapter IN ('hls.js', 'native_hls', 'unknown')),
    PRIMARY KEY ("project_id", "session_id", "kind", "network_kind", "adapter", "reason")
);

CREATE INDEX "idx_auth_issuance_counters_expires" ON "auth_issuance_counters" ("expires_at");

CREATE INDEX "idx_playback_events_dedup" ON "playback_events" ("project_id", "session_id", "sequence_number");

CREATE INDEX "idx_playback_events_session_canonical" ON "playback_events" ("project_id", "session_id", "server_received_at", "sequence_number", "ingest_sequence");

CREATE UNIQUE INDEX "idx_ingest_streams_active_display_name" ON "ingest_streams" ("project_id", "display_name") WHERE "status" != 'ended';

CREATE INDEX "idx_project_token_generations_project" ON "project_token_generations" ("project_id", "created_at");

CREATE INDEX "idx_srt_health_samples_dedupe" ON "srt_health_samples" ("project_id", "stream_id", "connection_id", "source_observed_at", "source_sequence");

CREATE INDEX "idx_srt_health_samples_stream_ingested" ON "srt_health_samples" ("project_id", "stream_id", "ingested_at", "id");

CREATE INDEX "idx_stream_sessions_state" ON "stream_sessions" ("state");

CREATE INDEX "idx_stream_sessions_project_started" ON "stream_sessions" ("project_id", "started_at", "session_id");

CREATE INDEX "idx_ingest_routing_rules_stream" ON "ingest_routing_rules" ("project_id", "stream_id");

CREATE INDEX "idx_stream_keys_stream" ON "stream_keys" ("project_id", "stream_id", "deactivated_at");

CREATE UNIQUE INDEX "idx_stream_keys_active_unique" ON "stream_keys" ("project_id", "key_hash") WHERE "deactivated_at" IS NULL;

CREATE INDEX "idx_stream_lifecycle_events_stream" ON "stream_lifecycle_events" ("project_id", "stream_id", "occurred_at");

CREATE INDEX "idx_stream_session_boundaries_session" ON "stream_session_boundaries" ("project_id", "session_id");
