#!/usr/bin/env bash
# Rendert .security/vulnignore.yaml -> .security/.trivyignore (Plain-Text).
#
# vulnignore.yaml ist Audit-Source-of-Truth (mit reason/expires/scope-
# Feldern, die Trivy nicht direkt konsumieren kann); .trivyignore ist
# das maschinenlesbare Tool-Format (eine CVE-ID pro Zeile, Kommentare
# mit "# ").
#
# Ausserdem prueft das Script, dass kein Eintrag das `expires`-Datum
# ueberschritten hat — abgelaufene Eintraege brechen den Lauf, damit
# Wartung erzwungen wird (plan-0.8.5 Tranche 1 vulnignore.yaml-
# Wartungsregel; volle automatische Erinnerung kommt mit plan-0.9.5).
#
# Usage:
#   bash scripts/render-trivyignore.sh
# Output:
#   .security/.trivyignore (overwrites)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="${ROOT_DIR}/.security/vulnignore.yaml"
TARGET="${ROOT_DIR}/.security/.trivyignore"

if [[ ! -f "${SOURCE}" ]]; then
    echo "render-trivyignore: ${SOURCE} not found" >&2
    exit 1
fi

today_epoch="$(date -u +%s)"

# Wir lesen einen einfachen YAML-Subgraph aus:
#   trivy:
#     ignore:
#       - id: CVE-...
#         reason: "..."
#         expires: YYYY-MM-DD
#         scope: "..."
#
# yq waere bequemer, ist aber nicht ueberall installiert. Awk reicht
# fuer das Schema, weil wir die Struktur strikt halten.

awk -v today="${today_epoch}" '
    BEGIN {
        in_trivy = 0; in_ignore = 0
        cur_id = ""; cur_reason = ""; cur_expires = ""; cur_scope = ""
        had_error = 0
        print "# Generated by scripts/render-trivyignore.sh from .security/vulnignore.yaml"
        print "# DO NOT EDIT this file directly — change vulnignore.yaml and re-run."
    }

    /^trivy:[[:space:]]*$/ { in_trivy = 1; next }
    /^[a-zA-Z]/ && !/^trivy:/ { in_trivy = 0; in_ignore = 0 }

    in_trivy && /^[[:space:]]+ignore:[[:space:]]*$/ { in_ignore = 1; next }

    in_ignore && /^[[:space:]]*- id:[[:space:]]*/ {
        if (cur_id != "") { emit() }
        cur_id = $0
        sub(/^[[:space:]]*- id:[[:space:]]*/, "", cur_id)
        cur_reason = ""; cur_expires = ""; cur_scope = ""
        next
    }
    in_ignore && /^[[:space:]]+reason:[[:space:]]*/ {
        cur_reason = $0
        sub(/^[[:space:]]+reason:[[:space:]]*/, "", cur_reason)
        gsub(/^"|"$/, "", cur_reason)
        next
    }
    in_ignore && /^[[:space:]]+expires:[[:space:]]*/ {
        cur_expires = $0
        sub(/^[[:space:]]+expires:[[:space:]]*/, "", cur_expires)
        next
    }
    in_ignore && /^[[:space:]]+scope:[[:space:]]*/ {
        cur_scope = $0
        sub(/^[[:space:]]+scope:[[:space:]]*/, "", cur_scope)
        gsub(/^"|"$/, "", cur_scope)
        next
    }

    END { if (cur_id != "") emit(); exit had_error }

    function emit(   exp_epoch, cmd, line) {
        if (cur_expires == "") {
            print "render-trivyignore: " cur_id " has no `expires` field — abort." > "/dev/stderr"
            had_error = 1
            return
        }
        cmd = "date -u -d \"" cur_expires "\" +%s 2>/dev/null"
        cmd | getline exp_epoch
        close(cmd)
        if (exp_epoch == "" || exp_epoch + 0 < today + 0) {
            print "render-trivyignore: " cur_id " expired (" cur_expires ") — renew or remove the entry." > "/dev/stderr"
            had_error = 1
            return
        }
        print "# " cur_id " — " cur_reason " (expires " cur_expires ", scope " (cur_scope == "" ? "*" : cur_scope) ")"
        print cur_id
    }
' "${SOURCE}" > "${TARGET}.tmp"

if [[ -s "${TARGET}.tmp" ]]; then
    mv "${TARGET}.tmp" "${TARGET}"
    echo "render-trivyignore: wrote ${TARGET} ($(grep -c "^CVE-\|^GHSA-" "${TARGET}" || echo 0) entr$(grep -c "^CVE-\|^GHSA-" "${TARGET}" 2>/dev/null | awk '{print ($1==1?"y":"ies")}'))"
else
    rm -f "${TARGET}.tmp"
    echo "render-trivyignore: no entries — removed ${TARGET}"
    rm -f "${TARGET}"
fi
