#!/usr/bin/env bash
# Rendert.security/vulnignore.yaml ->.security/.trivyignore (Plain-Text).
#
# vulnignore.yaml ist Audit-Source-of-Truth (mit reason/expires/scope-
# Feldern, die Trivy nicht direkt konsumieren kann);.trivyignore ist
# das maschinenlesbare Tool-Format (eine CVE-ID pro Zeile, Kommentare
# mit "# ").
#
# Ausserdem prueft das Script, dass kein Eintrag das `expires`-Datum
# ueberschritten hat — abgelaufene Eintraege brechen den Lauf, damit
# Wartung erzwungen wird ( vulnignore.yaml-
# Wartungsregel; volle automatische Erinnerung kommt mit ).
#
# Usage:
# bash scripts/render-trivyignore.sh [scope]
# bash scripts/render-trivyignore.sh mtrace-dashboard
# Output:
# .security/.trivyignore (overwrites)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="${ROOT_DIR}/.security/vulnignore.yaml"
TARGET="${ROOT_DIR}/.security/.trivyignore"
SCOPE_FILTER="${1:-}"
TARGET_TMP="${TARGET}.$$.tmp"

trap 'rm -f "${TARGET_TMP}"' EXIT

if [[ ! -f "${SOURCE}" ]]; then
    echo "render-trivyignore: ${SOURCE} not found" >&2
    exit 1
fi

today_epoch="$(date -u +%s)"

# Wir lesen einen einfachen YAML-Subgraph aus:
# trivy:
# ignore:
# - id: CVE-...
# reason: "..."
# expires: YYYY-MM-DD
# scope: "..."
#
# yq waere bequemer, ist aber nicht ueberall installiert. Awk reicht
# fuer das Schema, weil wir die Struktur strikt halten.

awk -v today="${today_epoch}" -v scope_filter="${SCOPE_FILTER}" '
    BEGIN {
        in_trivy = 0; in_ignore = 0
        cur_id = ""; cur_reason = ""; cur_expires = ""; cur_scope = ""
        had_error = 0
        print "# Generated by scripts/render-trivyignore.sh from .security/vulnignore.yaml"
        print "# DO NOT EDIT this file directly — change vulnignore.yaml and re-run."
    }

    /^trivy:[[:space:]]*$/ { in_trivy = 1; next }
    /^[a-zA-Z]/ && !/^trivy:/ { in_trivy = 0; in_ignore = 0 }

    in_trivy && /^[[:space:]]+ignore:[[:space:]]*$/ { in_ignore = 1; next }

    in_ignore && /^[[:space:]]*- id:[[:space:]]*/ {
        if (cur_id != "") { emit() }
        cur_id = $0
        sub(/^[[:space:]]*- id:[[:space:]]*/, "", cur_id)
        cur_reason = ""; cur_expires = ""; cur_scope = ""
        next
    }
    in_ignore && /^[[:space:]]+reason:[[:space:]]*/ {
        cur_reason = $0
        sub(/^[[:space:]]+reason:[[:space:]]*/, "", cur_reason)
        gsub(/^"|"$/, "", cur_reason)
        next
    }
    in_ignore && /^[[:space:]]+expires:[[:space:]]*/ {
        cur_expires = $0
        sub(/^[[:space:]]+expires:[[:space:]]*/, "", cur_expires)
        next
    }
    in_ignore && /^[[:space:]]+scope:[[:space:]]*/ {
        cur_scope = $0
        sub(/^[[:space:]]+scope:[[:space:]]*/, "", cur_scope)
        gsub(/^"|"$/, "", cur_scope)
        next
    }

    END { if (cur_id != "") emit(); exit had_error }

    function trim(s) {
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", s)
        return s
    }

    function scope_matches(scope,   n, i, parts, item) {
        if (scope_filter == "") {
            return 1
        }
        if (scope == "") {
            return 0
        }
        n = split(scope, parts, ",")
        for (i = 1; i <= n; i++) {
            item = trim(parts[i])
            if (item == "*" || item == scope_filter) {
                return 1
            }
        }
        return 0
    }

    function emit(   exp_epoch, cmd, line) {
        if (cur_expires == "") {
            print "render-trivyignore: " cur_id " has no `expires` field — abort." > "/dev/stderr"
            had_error = 1
            return
        }
        cmd = "date -u -d \"" cur_expires "\" +%s 2>/dev/null"
        cmd | getline exp_epoch
        close(cmd)
        if (exp_epoch == "" || exp_epoch + 0 < today + 0) {
            print "render-trivyignore: " cur_id " expired (" cur_expires ") — renew or remove the entry." > "/dev/stderr"
            had_error = 1
            return
        }
        if (!scope_matches(cur_scope)) {
            return
        }
        print "# " cur_id " — " cur_reason " (expires " cur_expires ", scope " (cur_scope == "" ? "*" : cur_scope) ")"
        print cur_id
    }
' "${SOURCE}" > "${TARGET_TMP}"

if [[ -s "${TARGET_TMP}" ]]; then
    mv "${TARGET_TMP}" "${TARGET}"
    entry_count="$(grep -Ec '^(CVE-|GHSA-)' "${TARGET}" || true)"
    entry_word="$(awk -v count="${entry_count}" 'BEGIN { print (count == 1 ? "entry" : "entries") }')"
    echo "render-trivyignore: wrote ${TARGET} (${entry_count} ${entry_word})"
else
    echo "render-trivyignore: no entries — removed ${TARGET}"
    rm -f "${TARGET}"
fi
