package application

import (
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/pt9912/m-trace/apps/api/hexagon/domain"
)

// MediaMTX-Konfigurations-Generator für `0.11.0` Tranche 3
// (NF-13 / RAK-68). Erzeugt aus einer Liste aktiver IngestStreams ein
// MediaMTX-YAML-Artefakt — keine direkte Manipulation laufender
// MediaMTX-Server, keine produktive Auth-Hooks (`0.11.0`-Out-of-
// Scope, R-15).
//
// Sicherheitsprofil:
//   - Klartext-Stream-Keys landen NIE in der generierten YAML.
//     Ausschließlich Stream-Display-Name (sanitized) und
//     `key_fingerprint` werden als Pfad-Bezeichner und
//     Audit-Comment ausgegeben.
//   - Output ist deterministisch — Streams werden alphabetisch nach
//     `display_name` sortiert, damit zwei Aufrufe mit derselben
//     Eingabe byte-gleiche YAML produzieren (Fixture-/Smoke-tauglich).
//
// MediaMTX-Format: `srt: yes`/`rtmp: yes`-Toggles plus `paths:`-Block
// mit einer Pfad-Entry pro Stream. Wir beschränken uns auf das
// Minimum, das die `examples/`-Lab-Stacks bereits erfolgreich nutzen.

// ErrMediaMTXConfigNoStreams signalisiert, dass der Aufrufer ein
// Config-Artefakt ohne aktive Streams angefordert hat. Der HTTP-
// Adapter mappt das auf `503 media_server_config_unavailable`.
var ErrMediaMTXConfigNoStreams = errors.New("ingest: no active streams to generate media-server config")

// MediaMTXConfigInput bündelt die Eingaben aus dem Use-Case.
// `Target` liefert `ConfigPath`/`HLSURLTemplate` — diese erscheinen
// als YAML-Comments und beeinflussen das Wire-Format nicht.
type MediaMTXConfigInput struct {
	Target  domain.MediaServerTarget
	Streams []domain.IngestStream
}

// MediaMTXConfigArtifact ist die generierte Sicht: das YAML als
// Bytes, plus eine Warnings-Liste (z. B. wenn ein Stream wegen
// fehlender Endpoint-Daten übersprungen wurde).
type MediaMTXConfigArtifact struct {
	YAML     string
	Warnings []string
}

// GenerateMediaMTXConfig erzeugt das YAML-Artefakt deterministisch.
// Streams werden nach `DisplayName` sortiert; pro Stream entsteht
// eine `paths:`-Entry mit `source: publisher`. SRT- und RTMP-
// Toggles werden eingeschaltet, wenn mindestens ein Stream das
// Protokoll nutzt.
func GenerateMediaMTXConfig(input MediaMTXConfigInput) (MediaMTXConfigArtifact, error) {
	if len(input.Streams) == 0 {
		return MediaMTXConfigArtifact{}, ErrMediaMTXConfigNoStreams
	}
	if input.Target.Kind != domain.MediaServerKindMediaMTX {
		return MediaMTXConfigArtifact{}, fmt.Errorf("ingest: media-server config generator supports only mediamtx, got %q", input.Target.Kind)
	}

	streams := make([]domain.IngestStream, 0, len(input.Streams))
	streams = append(streams, input.Streams...)
	sort.SliceStable(streams, func(i, j int) bool {
		return streams[i].DisplayName < streams[j].DisplayName
	})

	srtNeeded := false
	rtmpNeeded := false
	for _, s := range streams {
		switch s.Protocol {
		case domain.IngestProtocolSRT:
			srtNeeded = true
		case domain.IngestProtocolRTMP:
			rtmpNeeded = true
		}
	}

	var b strings.Builder
	b.WriteString("# Generated by apps/api ingest-control (plan-0.11.0 Tranche 3, RAK-68).\n")
	b.WriteString("# DO NOT EDIT — this artefact is reproducible from the project's\n")
	b.WriteString("# active IngestStream list and the MediaServerTarget.\n")
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# Target: %s (%s)\n", input.Target.ID, input.Target.Kind)
	if input.Target.HLSURLTemplate != "" {
		fmt.Fprintf(&b, "# HLS URL template: %s\n", input.Target.HLSURLTemplate)
	}
	if input.Target.ControlAPIURL != "" {
		fmt.Fprintf(&b, "# Control API URL:  %s\n", input.Target.ControlAPIURL)
	}
	b.WriteString("\n")
	b.WriteString("api: yes\n")
	b.WriteString("apiAddress: :9997\n")
	if srtNeeded {
		b.WriteString("srt: yes\n")
		b.WriteString("srtAddress: :8890\n")
	} else {
		b.WriteString("srt: no\n")
	}
	if rtmpNeeded {
		b.WriteString("rtmp: yes\n")
		b.WriteString("rtmpAddress: :1935\n")
	} else {
		b.WriteString("rtmp: no\n")
	}
	b.WriteString("hls: yes\n")
	b.WriteString("hlsAddress: :8889\n")
	b.WriteString("\n")
	b.WriteString("paths:\n")

	warnings := []string{}
	for _, s := range streams {
		pathName, ok := sanitizePathName(s.DisplayName)
		if !ok {
			warnings = append(warnings, fmt.Sprintf("stream %q has unsupported display_name characters; skipped", s.DisplayName))
			continue
		}
		fmt.Fprintf(&b, "  %s:\n", pathName)
		b.WriteString("    source: publisher\n")
		fmt.Fprintf(&b, "    # stream_id: %s, protocol: %s, key_fingerprint: %s\n",
			s.ID, s.Protocol, s.Key.Fingerprint)
	}

	return MediaMTXConfigArtifact{YAML: b.String(), Warnings: warnings}, nil
}

// sanitizePathName erzwingt einen MediaMTX-konformen Pfad-Identifier.
// MediaMTX akzeptiert YAML-Keys aus `[A-Za-z0-9_-]`; alles andere
// wird auf `_` gemappt. Leere oder rein-symbolische Display-Names
// liefern `false`, sodass der Generator den Stream auslässt und
// einen Warning emittiert.
func sanitizePathName(displayName string) (string, bool) {
	if strings.TrimSpace(displayName) == "" {
		return "", false
	}
	var b strings.Builder
	for _, r := range strings.ToLower(displayName) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '_' || r == '-':
			b.WriteRune(r)
		case r == ' ' || r == '.':
			b.WriteRune('_')
		default:
			// Ignore non-printable / unusable runes.
		}
	}
	out := b.String()
	if out == "" || strings.Trim(out, "_-") == "" {
		return "", false
	}
	return out, true
}
