micronaut:
  application:
    name: m-trace-api
  server:
    port: 8080
    max-request-size: 256KB
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
